apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: pensjonskalkulator
  name: pensjonskalkulator-uinnlogget
  namespace: pensjonskalkulator
spec:
  image: {{image}} # Placeholder variable to be replaced by the CI/CD pipeline
  ingresses:
  # - https://sandbox.ekstern.dev.nav.no/pensjon/kalkulator-uinnlogget
  port: 8080
  replicas:
    max: 2
    min: 2
  resources:
    requests:
      cpu: 200m
      memory: 128Mi