  name: workflow-uinnlogget
  on:
    push: 
      branches:
        - main
        - dev-workflows
    
  jobs:
    build-and-publish:
      name: Bygg, test og publiser docker image
      timeout-minutes: 15
      runs-on: ubuntu-latest
      permissions:
        packages: read
        contents: read
        id-token: write
      outputs:
        image: ${{ steps.docker-build-push.outputs.image }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: 'npm'
            registry-url: 'https://npm.pkg.github.com'

        - name: Install npm dependencies
          run: npm ci
          env:
            NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        #Kode under er for å hente openapi schema fra backend og generere types
        # - name: Fetch openapi backend types
        #   run: npx openapi-typescript ${{ github.event.inputs.prod == 'true' && 'https://www.nav.no/pensjon/kalkulator/v3/api-docs/current' || 'https://staging.ekstern.dev.nav.no/pensjon/kalkulator/v3/api-docs/current' }} -o ./src/types/schema.d.ts
        # - name: Format backend scheme
        #   run: npm run format:types
        - name: Run lint
          run: npm run lint
        - name: Build application
          run: npm run build
        - name: docker-build-push
          if: github.ref_name == 'main' || startsWith(github.ref_name, 'dev-')
          uses: nais/docker-build-push@v0
          id: docker-build-push
          with:
            team: pensjonskalkulator
            dockerfile: .docker/Dockerfile
            identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
            project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
        - name: deploy-dev
          uses: nais/deploy/actions/deploy@v2
          env:
            CLUSTER: dev-gcp
            RESOURCE: .nais/app.yml
            VAR: image=${{ steps.docker-build-push.outputs.image }}


    codeql-analyse:
      if: github.ref_name == 'main' || startsWith(github.ref_name, 'dev-')
      name: codeql-analyse
      timeout-minutes: 15
      runs-on: ubuntu-latest
      permissions:
        contents: read
        actions: read
        security-events: write
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Initialize CodeQL
          uses: github/codeql-action/init@v3
          with:
            queries: security-and-quality
            languages: 'javascript'
        - name: Autobuild
          uses: github/codeql-action/autobuild@v3
        - name: Perform CodeQL Analysis
          uses: github/codeql-action/analyze@v3
          with:
            category: "/language:javascript"

    # nais-deploy:
    #   needs: build-and-publish
    #   runs-on: ubuntu-latest
    #   permissions: write-all
      # uses: navikt/flex-github-actions-workflows/.github/workflows/nais-deploy-dev-og-prod.yml@main
      # with:
      #   image: ${{ needs.build-and-publish.outputs.image }}
      #   app: ${{ inputs.app }}
      #   dev-only: ${{ inputs.dev-only }}
      #   nais-template: .nais/app.yaml
      #   dev-vars: image=.nais/app.yaml
      # secrets: inherit
      